#include <iostream>
#include <cstdlib>

using namespace std;

int main()
{
    cout << "Linear sieve" << endl;
    cout << "Prime numbers in a range <2;n> generated by linear sieve" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n<2);

    const int size = n-1;
    bool* is_prime = new bool[size];
    for(bool* ptr = is_prime; ptr != is_prime+size; ++ptr)
        *(ptr) = true;


    int p=2, q=2;
    while(p*q <= n)
    {
        //cout << "p: " << p << "   q: " << q << "   x: " << x << endl;
        if(*(is_prime + q - 2))
        {
            int x = p*q;
            while(x <= n)
            {
                *(is_prime + x - 2) = false;
                x *= p;
            }
        }
        ++q;
        if(p*q > n)
        {
            ++p;
            while(*(is_prime + p - 2) == false)
                ++p;
            q = p;
        }
    }


    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    int counter = 0;
    bool* ptr = is_prime;
    for(int i=2; i <= n; ++i, ++ptr)
    {
        if(*ptr)
            cout << ++counter << ": " << i << endl;
    }


    delete[] is_prime;

    cout << endl;
    system("pause");
    return 0;
}
