#include <iostream>
#include <cstdlib>
#include <cmath>

using namespace std;

int main()
{
    cout << "Eratosthenes' sieve" << endl;
    cout << "Prime numbers in a range <2;n> generated by Eratosthenes' sieve" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n<2);

    bool* is_prime = new bool[n-1];
    for(bool* ptr = is_prime; ptr != is_prime+n-1; ++ptr)
        *(ptr) = true;


    int square_root = sqrt(n);
    for(int i = 2; i <= square_root; ++i)
    {
        if(*(is_prime + i - 2))
        {
            int a = i*i;
            while(a <= n)
            {
                *(is_prime + a - 2) = false;
                a += i;
            }
        }
    }


    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    int counter = 0;
    bool* ptr = is_prime;
    for(int i=2; i <= n; ++i, ++ptr)
    {
        if(*ptr)
            cout << ++counter << ": " << i << endl;
    }


    cout << endl;
    system("pause");
    return 0;
}
