#include <iostream>
#include <cstdlib>
#include <cmath>

using namespace std;

int main()
{
    cout << "Eratosthenes' sieve" << endl;
    cout << "Prime numbers in a range <2;n> generated by Eratosthenes' sieve" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n<2);

    const int size = ceil(n/2.0)-1;
    bool* is_prime = new bool[size];
    for(bool* ptr = is_prime; ptr != is_prime+size; ++ptr)
        *(ptr) = true;


    int square_root = sqrt(n);
    for(int i=3; i <= square_root; i+=2)
    {
        int index = (i-3)/2;
        if(*(is_prime + index))
        {
            int a = (i*i-3)/2;
            while(a < size)
            {
                *(is_prime + a) = false;
                a += i;
            }
        }
    }




    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    int counter = 0;

    if(n >= 2)
        cout << ++counter << ": 2" << endl;

    bool* ptr = is_prime;
    for(int i=3; i <= n; i+=2, ++ptr)
    {
        if(*ptr)
            cout << ++counter << ": " << i << endl;
    }

    delete[] is_prime;


    cout << endl;
    system("pause");
    return 0;
}
