#include <iostream>
#include <cstdlib>
#include <cmath>

using namespace std;

int main()
{
    cout << "Eratosthenes' sieve" << endl;
    cout << "Prime numbers in a range <2;n> generated by Eratosthenes' sieve" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n<2);

    const int size = ceil(n/2.0)-1;
    bool* is_prime = new bool[size];
    for(bool* ptr = is_prime; ptr != is_prime+size; ++ptr)
        *(ptr) = true;

    int i = 3, p = 0, q = 3;
    while(p < size)
    {
        if(*(is_prime + p))
        {
            int index = q;
            while(index < size)
            {
                *(is_prime + index) = false;
                index += i;
            }
        }
        ++p;
        q += 4*(p+1);
        i += 2;
    }





    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    int counter = 0;

    if(n >= 2)
        cout << ++counter << ": 2" << endl;

    bool* ptr = is_prime;
    for(int i=3; i <= n; i+=2, ++ptr)
    {
        if(*ptr)
            cout << ++counter << ": " << i << endl;
    }

    delete[] is_prime;

    cout << endl;
    system("pause");
    return 0;
}

