#include <iostream>
#include <cstdlib>

using namespace std;

int main()
{
    cout << "Prime numbers in a range <2;n> generated by division check" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n < 2);
    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    int counter = 0;
    for(int i=2; i<=n; ++i)
    {
        bool is_prime = true;
        for(int j=2; j<i; ++j)
        {
            if(i%j == 0)
            {
                is_prime = false;
                break;
            }
        }
        if(is_prime)
            cout << ++counter << ": " << i << endl;
    }



    cout << endl;
    system("pause");
    return 0;
}
