#include <iostream>
#include <cstdlib>
#include <cmath>
#include <vector>

using namespace std;

int main()
{
    cout << "Prime numbers in a range <2;n> generated by division check" << endl << endl;

    int n;
    cout << "n: ";
    do{
        cin >> n;
    }while(n < 2);
    cout << endl << "Prime numbers in a range <2;" << n << ">:" << endl;

    vector<int> primes;
    vector<int>::iterator it;

    int counter = 0;
    if(n >= 2)
    {
        cout << ++counter << ": 2" << endl;
        primes.push_back(2);
    }
    if(n >= 3)
    {
        cout << ++counter << ": 3" << endl;
        primes.push_back(3);
    }

    for(int i=1; 6*i-1<=n; ++i)
    {
        int a = 6*i - 1;

        bool is_prime = true;
        int square_root = sqrt(a);
        for(it = primes.begin(); *it <= square_root; ++it)
            if(a % (*it) == 0)
            {
                is_prime = false;
                break;
            }
        if(is_prime)
        {
            cout << ++counter << ": " << a << endl;
            primes.push_back(a);
        }

        is_prime = true;
        a += 2;
        square_root = sqrt(a);
        for(it = primes.begin(); *it <= square_root; ++it)
            if(a % (*it) == 0)
            {
                is_prime = false;
                break;
            }
        if(is_prime)
        {
            cout << ++counter << ": " << a << endl;
            primes.push_back(a);
        }
    }

    cout << endl;
    system("pause");
    return 0;
}
